insert into person values ('gavin', 'Gavin King', 'foobar')
insert into person values ('emmanuel', 'Emmanuel Bernard', 'secret')
insert into person values ('steve', 'Steve Ebersole', 'secret')
insert into person values ('max', 'Max Andersen', 'secret')
insert into person values ('sergey', 'Sergey Koshcheyev', 'secret')
insert into project values('HHH', 'Hibernate 3 Core')
insert into project values('HA', 'Hibernate Annotations')
insert into project values('HEM', 'Hibernate Entity Manager')
insert into project values('HT', 'Hibernate Tools')
insert into project values('NH', 'NHibernate')
insert into project values('SEAM', 'JBoss Seam')
insert into project_person (project_name, developers_username) values ('HHH', 'gavin')
insert into project_person (project_name, developers_username) values ('HEM', 'emmanuel')
insert into project_person (project_name, developers_username) values ('HA', 'emmanuel')
insert into project_person (project_name, developers_username) values ('SEAM', 'gavin')
insert into project_person (project_name, developers_username) values ('HHH', 'steve')
insert into project_person (project_name, developers_username) values ('NH', 'sergey')
insert into project_person (project_name, developers_username) values ('HT', 'max')