insert into user values ('gavin', 'Gavin King', 'foobar')
insert into user values ('emmanuel', 'Emmanuel Bernard', 'secret')
insert into project values('HHH', 'Hibernate 3 Core')
insert into project values('HA', 'Hibernate Annotations')
insert into project values('HEM', 'Hibernate Entity Manager')
insert into project values('NH', 'NHibernate')
insert into project values('SEAM', 'JBoss Seam')
insert into project_user (project_name, developers_username) values ('HHH', 'gavin')
insert into project_user (project_name, developers_username) values ('HHH', 'emmanuel')
insert into project_user (project_name, developers_username) values ('HA', 'emmanuel')
insert into project_user (project_name, developers_username) values ('SEAM', 'gavin')