#!/bin/sh
############################################
#
# seam-gen - Seam project and code generator
#
############################################

# Validate the JDK installation
if [ -z "$JAVA_HOME" ]; then
    echo "The JAVA_HOME environment variable is not set"
    echo "Please point it to a valid JDK installation"
    exit 1
elif [ ! -x "$JAVA_HOME"/bin/javac ]; then 
    echo "The JAVA_HOME environment variable should point to a JDK, not a JRE"
    exit 1
fi

DIRNAME=`dirname $0`
WORKING_DIR=$PWD

if [ -z "$SEAM_HOME" ]; then
    # get the full path (without any relative bits)
    SEAM_HOME=`readlink -f $DIRNAME`
fi

SEAM_GEN_DIR="$SEAM_HOME/seam-gen"
SEAM_COMMAND="${1}"

# OS specific support (must be 'true' or 'false').
cygwin=false;
case "`uname`" in
    CYGWIN*)
        cygwin=true
        ;;
esac

if [ -z "$SEAM_COMMAND" ]; then
    cat $SEAM_GEN_DIR/USAGE
elif [ "$SEAM_COMMAND" = help ]; then
    cat $SEAM_GEN_DIR/README
elif $cygwin; then
   java -cp "${JAVA_HOME}\lib\tools.jar;${SEAM_HOME}\build\lib\ant-launcher.jar;${SEAM_HOME}\build\lib\ant-nodeps.jar;${SEAM_HOME}\build\lib\ant.jar" -Dant.home=${SEAM_HOME}\lib org.apache.tools.ant.launch.Launcher -buildfile "${SEAM_GEN_DIR}\build.xml" -Dworking.dir=$WORKING_DIR ${*}
else
   java -cp "${JAVA_HOME}/lib/tools.jar:${SEAM_HOME}/build/lib/ant-launcher.jar:${SEAM_HOME}/build/lib/ant-nodeps.jar:${SEAM_HOME}/build/lib/ant.jar" -Dant.home=${SEAM_HOME}/lib org.apache.tools.ant.launch.Launcher -buildfile "${SEAM_GEN_DIR}/build.xml" -Dworking.dir=$WORKING_DIR ${*}
fi
