//insert into DIRECTORY (DIR_ID, OBJ_VERSION, NAME, WIKINAME, PARENT_DIR_ID, DIR_POSITION, DEFAULT_DOCUMENT_ID) values (1, 1, 'This Is FooA', 'ThisIsFooA', null, null, null);
//insert into DIRECTORY (DIR_ID, OBJ_VERSION, NAME, WIKINAME, PARENT_DIR_ID, DIR_POSITION, DEFAULT_DOCUMENT_ID) values (2, 1, 'This Is FooB', 'ThisIsFooB', null, null, null);
//insert into DIRECTORY (DIR_ID, OBJ_VERSION, NAME, WIKINAME, PARENT_DIR_ID, DIR_POSITION, DEFAULT_DOCUMENT_ID) values (3, 1, 'This Is FooC', 'ThisIsFooC', null, null, null);
//insert into DOCUMENT (DOC_ID, OBJ_VERSION, NAME, WIKINAME, DIRECTORY_ID, DOC_POSITION, CONTENT) values (1, 1, 'This Is Document FooA1', 'ThisIsDocumentFooA1', 1, 0, 'This is /some/ *text*.');
//insert into FOO (ID, NAME, VERSION) values (1, 'Test', 0)

insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, NODE_POSITION, DEFAULT_DOCUMENT_ID, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CREATED_ON) values (1, 'DIRECTORY', 1, 0, null, 0, 'ROOT', 'ROOT', false, '1976-06-26 11:11:11')

insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, DEFAULT_DOCUMENT_ID, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CREATED_ON, LAST_MODIFIED_ON) values (2, 'DIRECTORY', 2, 1, 0, null, 0, 'News', 'News', true, '2009-06-27 13:45:00', '2009-06-27 13:45:00' )
insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, DEFAULT_DOCUMENT_ID, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CREATED_ON, LAST_MODIFIED_ON) values (3, 'DIRECTORY', 3, 1, 1, null, 0, 'Documentation Area', 'DocumentationArea', true, '2009-06-27 13:45:00', '2009-06-27 13:45:00')
insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, DEFAULT_DOCUMENT_ID, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CREATED_ON, LAST_MODIFIED_ON) values (4, 'DIRECTORY', 4, 1, 2, null, 0, 'Download Overview', 'DownloadOverview', false, '2009-06-27 13:45:00', '2009-06-27 13:45:00')

insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CONTENT, CREATED_ON, LAST_MODIFIED_ON) values (5, 'DOCUMENT', 2, 2, 0, 0, 'Welcome!', 'Welcome', false,'[A link=>wiki://6] to some page, a [broken=>wiki://123], a normal link [=>wiki://7] and finally [=>Some page that does not exist] and a link to a [different area=>Documentation Area|FooBar].@@LF@@@@LF@@Seam Text is a human-friendly language for formatting text in blogs, forums and wikis. It''s easy to enter text in *bold*, /italic/, |monospace|, ~deleted~ or ^superscript^; you can easily enter links, lists, quotes and code blocks.@@LF@@@@LF@@[This is a link.=>http://hibernate.org]@@LF@@@@LF@@You can *not* enter HTML entities, even escaped: \&amp; \&lt; \&gt; \&quot; \&nbsp;@@LF@@@@LF@@And even emoticons: ;) :-) :-{ ;-)@@LF@@@@LF@@Here is an ordered list:@@LF@@@@LF@@#JBoss@@LF@@#Seam@@LF@@#Hibernate@@LF@@@@LF@@And this is an unordered list:@@LF@@@@LF@@=jBPM@@LF@@=Drools@@LF@@=Ajax4JSF@@LF@@=Facelets@@LF@@@@LF@@"Here is a quote from someone else"@@LF@@@@LF@@`<p>Here is some code</p>`@@LF@@@@LF@@And some plain HTML (restricted subset):@@LF@@@@LF@@<table style="border:1px solid blue;"><tr><td>Foo</td><td>Bar</td></tr></table>`','2009-06-27 13:45:00', '2009-06-27 13:45:00')
insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CONTENT, CREATED_ON, LAST_MODIFIED_ON) values (6, 'DOCUMENT', 2, 2, 1, 0, 'Foo', 'Foo', true, 'Welcome *to the* /Wiki/!', '2009-06-27 13:45:00', '2009-06-27 13:45:00')
insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CONTENT, CREATED_ON, LAST_MODIFIED_ON) values (7, 'DOCUMENT', 2, 2, 2, 0, 'Bar', 'Bar', true, 'Welcome *to the* /Wiki/!', '2009-06-27 13:45:00', '2009-06-27 13:45:00')

insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, DEFAULT_DOCUMENT_ID, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CREATED_ON, LAST_MODIFIED_ON) values (8, 'DIRECTORY', 3, 3, 0, null, 0, 'FAQ', 'FAQ', true, '2009-06-27 13:45:00', '2009-06-27 13:45:00')

insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CONTENT, CREATED_ON, LAST_MODIFIED_ON)  values (9, 'DOCUMENT', 3, 3, 1, 0, 'FooBar', 'FooBar', true, 'Another one', '2009-06-27 13:45:00', '2009-06-27 13:45:00')
insert into NODE (NODE_ID, NODE_TYPE, AREA_NR, PARENT_NODE_ID, NODE_POSITION, OBJ_VERSION, NAME, WIKINAME, MENU_ITEM, CONTENT, CREATED_ON, LAST_MODIFIED_ON)  values (10, 'DOCUMENT', 3, 8, 0, 0, 'An FAQ Page', 'AnFAQPage', true, 'FAQ!', '2009-06-27 13:45:00', '2009-06-27 13:45:00')
