insert into Users (username, password, name) values ('gavin', 'foobar', 'Gavin King')
insert into Users (username, password, name) values ('demo', 'demo', 'Demo User')
insert into Hotel (id, name, address, city, state, zip) values (1, 'Marriott Courtyard', 'Tower Place, Buckhead', 'Atlanta', 'GA', '30305')
insert into Hotel (id, name, address, city, state, zip) values (2, 'Doubletree', 'Tower Place, Buckhead', 'Atlanta', 'GA', '30305')
insert into Hotel (id, name, address, city, state, zip) values (3, 'W Hotel', 'Union Square, Manhattan', 'NY', 'NY', '10011')
insert into Hotel (id, name, address, city, state, zip) values (4, 'W Hotel', 'Lexington Ave, Manhattan', 'NY', 'NY', '10011')
insert into Hotel (id, name, address, city, state, zip) values (5, 'Hotel Rouge', 'Dupont Circle', 'Washington', 'DC', '20036')
insert into Hotel (id, name, address, city, state, zip) values (6, '70 Park Avenue Hotel', '70 Park Avenue', 'NY', 'NY', '10011')
insert into Hotel (id, name, address, city, state, zip) values (8, 'Conrad Miami', '1395 Brickell Ave', 'Miami', 'FL', '33131')
insert into Hotel (id, name, address, city, state, zip) values (9, 'Sea Horse Inn', '2106 N Clairemont Ave', 'Eau Claire', 'WI', '54703')
insert into Hotel (id, name, address, city, state, zip) values (10, 'Super 8 Eau Claire Campus Area', '1151 W Macarthur Ave', 'Eau Claire', 'WI', '54701')
insert into Hotel (id, name, address, city, state, zip) values (11, 'Marriot Downtown', '55 Fourth Street', 'San Francisco', 'CA', '94103')
insert into Hotel (id, name, address, city, state, zip) values (12, 'Hilton Diagonal Mar', 'Diagonal', 'Barcelona', 'Spain', '')
insert into Hotel (id, name, address, city, state, zip) values (13, 'Hilton Tel Aviv', '', 'Tel Aviv', 'Israel', '')
insert into Hotel (id, name, address, city, state, zip) values (14, 'InterContinental Tokyo Bay', 'Hamamatsucho', 'Tokyo', 'Japan', '')
insert into Hotel (id, name, address, city, state, zip) values (15, 'Hotel Beaulac', '', 'Neuchatel', 'Switzerland', '')
insert into Hotel (id, name, address, city, state, zip) values (16, 'Conrad Treasury Place', '', 'Brisbane', 'QLD', '')
insert into Hotel (id, name, address, city, state, zip) values (17, 'Ritz Carlton', 'Sherbrooke Ave', 'Montreal', 'Quebec', '')
insert into Hotel (id, name, address, city, state, zip) values (18, 'Ritz Carlton', 'Peachtree Rd, Buckhead', 'Atlanta', 'GA', '30326')
insert into Hotel (id, name, address, city, state, zip) values (19, 'Swissotel', '', 'Sydney', 'NSW', '')
