-- MySQL magic!
set session sql_mode='PIPES_AS_CONCAT'

INSERT INTO `ROLES` (`ROLE_ID`, `ACCESS_LEVEL`, `CREATED_ON`, `DISPLAY_NAME`, `NAME`, `OBJ_VERSION`) VALUES (1,1000,'2006-06-27 13:45:00','Administrator','admin',0)
INSERT INTO `ROLES` (`ROLE_ID`, `ACCESS_LEVEL`, `CREATED_ON`, `DISPLAY_NAME`, `NAME`, `OBJ_VERSION`) VALUES (2,0,'2006-06-27 13:45:00','Guest','guest',0)
INSERT INTO `ROLES` (`ROLE_ID`, `ACCESS_LEVEL`, `CREATED_ON`, `DISPLAY_NAME`, `NAME`, `OBJ_VERSION`) VALUES (3,1,'2006-06-27 13:45:00','Member','member',0)

INSERT INTO `USER_PROFILE` (`USER_PROFILE_ID`, `BIO`, `CREATED_ON`, `IMAGE_DATA`, `IMAGE_CONTENT_TYPE`, `LOCATION`, `OCCUPATION`, `SIGNATURE`, `OBJ_VERSION`, `WEBSITE`) VALUES (1,NULL,'2006-06-27 13:45:00',NULL,NULL,NULL,NULL,NULL,0,NULL)
INSERT INTO `USER_PROFILE` (`USER_PROFILE_ID`, `BIO`, `CREATED_ON`, `IMAGE_DATA`, `IMAGE_CONTENT_TYPE`, `LOCATION`, `OCCUPATION`, `SIGNATURE`, `OBJ_VERSION`, `WEBSITE`) VALUES (2,NULL,'2006-06-27 13:45:00',NULL,NULL,NULL,NULL,NULL,0,NULL)

INSERT INTO `USERS` (`USER_ID`, `ACTIVATED`, `ACTIVATION_CODE`, `CREATED_ON`, `EMAIL`, `FIRSTNAME`, `LAST_LOGIN_ON`, `LASTNAME`, `PASSWORDHASH`, `USERNAME`, `OBJ_VERSION`, `USER_PROFILE_ID`, `MEMBER_HOME_WIKI_DIRECTORY_ID`) VALUES (1,'',NULL,'2006-06-27 13:45:00','admin@email.tld','System',NULL,'Administrator','21232f297a57a5a743894a0e4a801fc3','admin',0,1,NULL)
INSERT INTO `USERS` (`USER_ID`, `ACTIVATED`, `ACTIVATION_CODE`, `CREATED_ON`, `EMAIL`, `FIRSTNAME`, `LAST_LOGIN_ON`, `LASTNAME`, `PASSWORDHASH`, `USERNAME`, `OBJ_VERSION`, `USER_PROFILE_ID`, `MEMBER_HOME_WIKI_DIRECTORY_ID`) VALUES (2,false,NULL,'2006-06-27 13:45:00','guest','Anonymous',NULL,'Guest','guest','guest',0,2,NULL)

INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (1,1)
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (2,2)


INSERT INTO `WIKI_NODE` (`NODE_ID`, `AREA_NR`, `CREATED_ON`, `LAST_MODIFIED_ON`, `NAME`, `READ_ACCESS_LEVEL`, `OBJ_VERSION`, `WIKINAME`, `WRITE_ACCESS_LEVEL`, `WRITE_PROTECTED`, `CREATED_BY_USER_ID`, `LAST_MODIFIED_BY_USER_ID`, `PARENT_NODE_ID`) VALUES (1,1,'2006-09-23 13:45:00',NULL,'ROOT',0,0,'ROOT',1000,'',1,NULL,NULL)

INSERT INTO `WIKI_NODE` (`NODE_ID`, `AREA_NR`, `CREATED_ON`, `LAST_MODIFIED_ON`, `NAME`, `READ_ACCESS_LEVEL`, `OBJ_VERSION`, `WIKINAME`, `WRITE_ACCESS_LEVEL`, `WRITE_PROTECTED`, `CREATED_BY_USER_ID`, `LAST_MODIFIED_BY_USER_ID`, `PARENT_NODE_ID`) VALUES (2,2,'2006-09-23 13:45:00',NULL,'Start',0,0,'Start',0,false,1,NULL,1)

INSERT INTO `WIKI_NODE` (`NODE_ID`, `AREA_NR`, `CREATED_ON`, `LAST_MODIFIED_ON`, `NAME`, `READ_ACCESS_LEVEL`, `OBJ_VERSION`, `WIKINAME`, `WRITE_ACCESS_LEVEL`, `WRITE_PROTECTED`, `CREATED_BY_USER_ID`, `LAST_MODIFIED_BY_USER_ID`, `PARENT_NODE_ID`) VALUES(3,2,'2006-09-23 13:45:00',NULL,'Welcome!',0,1,'Welcome',0,false,1,NULL,2)

INSERT INTO `WIKI_NODE` (`NODE_ID`, `AREA_NR`, `CREATED_ON`, `LAST_MODIFIED_ON`, `NAME`, `READ_ACCESS_LEVEL`, `OBJ_VERSION`, `WIKINAME`, `WRITE_ACCESS_LEVEL`, `WRITE_PROTECTED`, `CREATED_BY_USER_ID`, `LAST_MODIFIED_BY_USER_ID`, `PARENT_NODE_ID`) VALUES(4,4,'2006-09-23 13:45:00',NULL,'Members',0,0,'Members',1000,'',1,NULL,1)

INSERT INTO `WIKI_NODE` (`NODE_ID`, `AREA_NR`, `CREATED_ON`, `LAST_MODIFIED_ON`, `NAME`, `READ_ACCESS_LEVEL`, `OBJ_VERSION`, `WIKINAME`, `WRITE_ACCESS_LEVEL`, `WRITE_PROTECTED`, `CREATED_BY_USER_ID`, `LAST_MODIFIED_BY_USER_ID`, `PARENT_NODE_ID`) VALUES (5,5,'2006-09-23 13:45:00',NULL,'Help',0,0,'Help',1000,'',1,NULL,1)

INSERT INTO `WIKI_NODE` (`NODE_ID`, `AREA_NR`, `CREATED_ON`, `LAST_MODIFIED_ON`, `NAME`, `READ_ACCESS_LEVEL`, `OBJ_VERSION`, `WIKINAME`, `WRITE_ACCESS_LEVEL`, `WRITE_PROTECTED`, `CREATED_BY_USER_ID`, `LAST_MODIFIED_BY_USER_ID`, `PARENT_NODE_ID`) VALUES (6,5,'2006-09-23 13:45:00',NULL,'Working with documents',0,0,'WorkingWithDocuments',1000,'',1,NULL,5)

INSERT INTO `WIKI_NODE` (`NODE_ID`, `AREA_NR`, `CREATED_ON`, `LAST_MODIFIED_ON`, `NAME`, `READ_ACCESS_LEVEL`, `OBJ_VERSION`, `WIKINAME`, `WRITE_ACCESS_LEVEL`, `WRITE_PROTECTED`, `CREATED_BY_USER_ID`, `LAST_MODIFIED_BY_USER_ID`, `PARENT_NODE_ID`) VALUES (7,5,'2006-09-23 13:45:00',NULL,'Wiki Text Markup',0,0,'WikiTextMarkup',1000,'',1,NULL,6) 

INSERT INTO `WIKI_FILE` (`NODE_ID`, `FILE_REVISION`) VALUES (3,0)
INSERT INTO `WIKI_FILE` (`NODE_ID`, `FILE_REVISION`) VALUES (7,0)

INSERT INTO `WIKI_DIRECTORY` (`NODE_ID`, `DESCRIPTION`, `NS_LEFT`, `NS_RIGHT`, `NS_THREAD`, `DEFAULT_FILE_ID`) VALUES (1,NULL,1,10,1,NULL)
INSERT INTO `WIKI_DIRECTORY` (`NODE_ID`, `DESCRIPTION`, `NS_LEFT`, `NS_RIGHT`, `NS_THREAD`, `DEFAULT_FILE_ID`) VALUES (2,NULL,2,3,1,3)
INSERT INTO `WIKI_DIRECTORY` (`NODE_ID`, `DESCRIPTION`, `NS_LEFT`, `NS_RIGHT`, `NS_THREAD`, `DEFAULT_FILE_ID`) VALUES (4,'Default member area',8,9,1,NULL)
INSERT INTO `WIKI_DIRECTORY` (`NODE_ID`, `DESCRIPTION`, `NS_LEFT`, `NS_RIGHT`, `NS_THREAD`, `DEFAULT_FILE_ID`) VALUES (5,'Help documents',4,7,1,NULL)
INSERT INTO `WIKI_DIRECTORY` (`NODE_ID`, `DESCRIPTION`, `NS_LEFT`, `NS_RIGHT`, `NS_THREAD`, `DEFAULT_FILE_ID`) VALUES (6,'Creating and editing wiki documents',5,6,1,NULL)

INSERT INTO `WIKI_DOCUMENT` (`NODE_ID`, `CONTENT`, `CONTENT_MACROS`, `ENABLE_COMMENT_FORM`, `ENABLE_COMMENTS`, `ENABLE_COMMENTS_ON_FEEDS`, `FOOTER`, `FOOTER_MACROS`, `HEADER`, `HEADER_MACROS`, `NAME_AS_TITLE`) VALUES (3,'Welcome to LaceWiki.\n\nLogin with admin-admin and rebuild the search index in the administration area.',NULL,true,true,true,NULL,NULL,NULL,NULL,true)

INSERT INTO `WIKI_DOCUMENT` (`NODE_ID`, `CONTENT`, `CONTENT_MACROS`, `ENABLE_COMMENT_FORM`, `ENABLE_COMMENTS`, `ENABLE_COMMENTS_ON_FEEDS`, `FOOTER`, `FOOTER_MACROS`, `HEADER`, `HEADER_MACROS`, `NAME_AS_TITLE`) VALUES (7,'Most content on this website (blogs, blog comments, wiki pages, user profiles) is rendered using the [Seam Text=>http://docs.jboss.com/seam/latest/reference/en/html/text.html] engine. If you are creating content, it helps to know a few simple tricks.\n\n++ Basic formatting\n\nYou can emphasize words using /italics/, *bold*, _underline_, ~strikeout~ or ^superscript^.\n\n`You can emphasize words using\n/italics/, *bold*, _underline_, ~strikeout~ or ^superscript^.`\n\nBut if you really want to type a special character such as \\/, \\* or \\+, you need to escape it with a \\\\.\n\n`But if you really want to type a special character\nsuch as \\/, \\* or \\+, you need to escape it with a \\\\.`\n\nAlternatively, you can use special characters freely inside |monospace text|.\n\n`Alternatively, you can use special characters freely\ninside |monospace text|.`\n\n++ Block formatting\n\nOf course, you can also use \\\"inline quotes\\\".\n\n\"And block quotes.\"\n\nAnd split text across several paragraphs.\n\n`Of course, you can also use \"inline quotes\".\n\n\"And block quotes.\"\n\nAnd split text across several paragraphs.`\n\nYou can create\n\n= unorderedlists\n= of stuff\n= like this\n\nor\n\n# numbered lists\n# of other things\n\n`You can create\n= unordered lists\n= of stuff\n= like this\n\nor\n\n# numbered lists\n# of other things`\n\nA third option for embedding text that uses special characters is to use a code block, delimited by *backticks*. For example:\n\n`for (int i=0; i<100; i++) {\n   log.info(\"Hello world!\");\n}`\n\n+ Here is a first-level heading\n\nHere is a normal paragraph.\n\n++ Here is a second-level heading\n\nAnd another paragraph.\n\n`+ Here is a first-level heading\n\nHere is a normal paragraph.\n\n++ Here is a second-level heading\n\nAnd another paragraph.`\n\n++ Links\n\nThe wiki has powerful handling for links.\n\nHTML links to [=>http://hibernate.org] or attach the link to [some link text=>http://hibernate.org].\nMy [e-mail address=>mailto:foo@bar.tld] will be automatically protected.\n\n`HTML links to [=>http://hibernate.org] or attach the\nlink to [some link text=>http://hibernate.org].\nMy [e-mail address=>mailto:foo@bar.tld] will be\nautomatically protected.`\n\nInternal wiki links simply use area and document\\/file names:\n\n= Link to  another document: \\[\\=\\>My Document\\] \n= Link to another document with link text: \\[A document\\=\\>My Document\\]\n= Link to another document in another area: \\[\\=\\>Another Area\\|My Document\\]\n= Link to an uploaded file or image: \\[\\=\\>My Upload\\]\n\nYou can even link to a [Hibernate JIRA issue=>hhh://2702], or a\n[Seam JIRA issue=>jbseam://1920].\n\n`You can even link to a [Hibernate JIRA issue=>hhh://2702],\nor a [Seam JIRA issue=>jbseam://1920].`\n\n++ Embedded HTML\n\nYou can even use <i>many</i> HTML tags directly, but <b>not</b> tags that would create a security vulnerability!\n\n`You can even use <i>many</i> HTML tags directly,\nbut <b>not</b> tags that would create a\nsecurity vulnerability!`',NULL,false,false,false,NULL,NULL,NULL,NULL,true)

INSERT INTO `WIKI_MENU_ITEM` (`DIRECTORY_ID`, `DISPLAY_POSITION`) VALUES (2,0)
INSERT INTO `WIKI_MENU_ITEM` (`DIRECTORY_ID`, `DISPLAY_POSITION`) VALUES (4,1)
INSERT INTO `WIKI_MENU_ITEM` (`DIRECTORY_ID`, `DISPLAY_POSITION`) VALUES (5,2)


INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (1,'wikiPreferences','baseUrl',NULL,NULL,NULL,NULL,'http://www.lacewiki.org',0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (2,'wikiPreferences','timeZone',NULL,NULL,NULL,NULL,'CET',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (3,'wikiPreferences','themeName',NULL,NULL,NULL,NULL,'default',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (4,'wikiPreferences','memberArea',NULL,NULL,NULL,NULL,'Members',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (5,'wikiPreferences','helpArea',NULL,NULL,NULL,NULL,'Help',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (6,'wikiPreferences','defaultDocumentId',3,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (7,'wikiPreferences','renderPermlinks',NULL,NULL,NULL,false,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (8,'wikiPreferences','permlinkSuffix',NULL,NULL,NULL,NULL,'.lace',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (9,'wikiPreferences','feedTitlePrefix',NULL,NULL,NULL,NULL,'LaceWiki - ',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (10,'wikiPreferences','purgeFeedEntriesAfterDays',999,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (11,'wikiPreferences','atSymbolReplacement',NULL,NULL,NULL,NULL,'(AT)',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (12,'wikiPreferences','mainMenuLevels',3,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (13,'wikiPreferences','mainMenuDepth',3,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (14,'wikiPreferences','mainMenuShowAdminOnly',NULL,NULL,NULL,false,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (15,'wikiPreferences','showDocumentCreatorHistory',NULL,NULL,NULL,'',NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (16,'wikiPreferences','showTags',NULL,NULL,NULL,'',NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (17,'wikiPreferences','showEmailToLoggedInOnly',NULL,NULL,NULL,'',NULL, true,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (20,'docEditorPreferences','minorRevisionEnabled',NULL,NULL,NULL,'',NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (21,'docEditorPreferences','regularEditAreaRows',15,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (22,'docEditorPreferences','regularEditAreaColumns',80,NULL,NULL,NULL,NULL,0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (30,'userManagementPreferences','activationCodeSalt',NULL,NULL,NULL,NULL,'MySecretSalt123',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (31,'userManagementPreferences','passwordRegex',NULL,NULL,NULL,NULL,'^[0-9A-Za-z]{6,15}',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (32,'userManagementPreferences','newUserInRole',NULL,NULL,NULL,NULL,'member',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (33,'userManagementPreferences','enableRegistration',NULL,NULL,NULL,'',NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (34,'userManagementPreferences','createHomeAfterUserActivation',NULL,NULL,NULL,false,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (35,'userManagementPreferences','homepageDefaultContent',NULL,NULL,NULL,NULL,'This is your homepage, login to edit it.',0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (40,'commentsPreferences','listAscending',NULL,NULL,NULL,false,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (41,'commentsPreferences','enableByDefault',NULL,NULL,NULL,'',NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (42,'commentsPreferences','threadedComments',NULL,NULL,NULL,'',NULL,0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (110,'lastModifiedDocumentsPreferences','numberOfItems',5,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (111,'lastModifiedDocumentsPreferences','showUsernames',NULL,NULL,NULL,'',NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (112,'lastModifiedDocumentsPreferences','documentTitleLength',20,NULL,NULL,NULL,NULL,0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (120,'blogDirectoryPreferences','pageSize',5,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (121,'blogDirectoryPreferences','recentHeadlines',10,NULL,NULL,NULL,NULL,0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (130,'feedTeasersPreferences','teaserTitle',NULL,NULL,NULL,NULL,'Site news feed:',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (131,'feedTeasersPreferences','feedIdentifier',1,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (132,'feedTeasersPreferences','numberOfTeasers',5,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (133,'feedTeasersPreferences','truncateDescription',200,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (134,'feedTeasersPreferences','showAuthor',NULL,NULL,NULL,'',NULL,0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (140,'flashPreferences','flashURL',NULL,NULL,NULL,NULL,'',0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (141,'flashPreferences','objectWidth',350,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (142,'flashPreferences','objectHeight',425,NULL,NULL,NULL,NULL,0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (170,'dirMenuPreferences','menuLevels',3,NULL,NULL,NULL,NULL,0,NULL,NULL)
INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (171,'dirMenuPreferences','menuDepth',3,NULL,NULL,NULL,NULL,0,NULL,NULL)

INSERT INTO `PREFERENCE` (`PREF_ID`, `COMPONENT_NAME`, `PROPERTY_NAME`, `LONG_VALUE`, `DOUBLE_VALUE`, `TIMESTAMP_VALUE`, `BOOLEAN_VALUE`, `STRING_VALUE`, `OBJ_VERSION`, `WIKI_DOCUMENT_ID`, `USER_ID`) VALUES (180,'forumPreferences','topicsPerPage',20,NULL,NULL,NULL,NULL,0,NULL,NULL)


INSERT INTO `FEED` (`FEED_ID`, `AUTHOR`, `DESCRIPTION`, `PUBLISHED_ON`, `TITLE`, `OBJ_VERSION`, `DIRECTORY_ID`) VALUES (1,'System Administrator',NULL,'2006-09-23 13:45:00','ROOT',0,1);

INSERT INTO `LINK_PROTOCOL` (`LINK_PROTOCOL_ID`, `LINK`, `PREFIX`, `OBJ_VERSION`) VALUES (1,'http://jira.jboss.com/jira/browse/JBSEAM-[[link]]','jbseam',0)
INSERT INTO `LINK_PROTOCOL` (`LINK_PROTOCOL_ID`, `LINK`, `PREFIX`, `OBJ_VERSION`) VALUES (2,'http://opensource.atlassian.com/projects/hibernate/browse/HHH-[[link]]','hhh',0)
INSERT INTO `LINK_PROTOCOL` (`LINK_PROTOCOL_ID`, `LINK`, `PREFIX`, `OBJ_VERSION`) VALUES (3,'http://www.youtube.com/watch?v=[[link]]','youtube',0)


-- More MySQL magic!
set session sql_mode=''
