package Permissions;

import java.security.Principal;

import org.jboss.seam.security.PermissionCheck;
import org.jboss.seam.security.Role;

rule AdminIsAMember
  salience 10
  no-loop
when
  Role(name == "admin")
  not Role(name == "member")
then
  assert(new Role("member"));
end;

rule AdminIsAGuest
  salience 10
  no-loop
when
  Role(name == "admin")
  not Role(name == "guest")
then
  assert(new Role("guest"));
end;

rule MemberIsAGuest
  salience 10
  no-loop
when
  Role(name == "member")
  not Role(name == "guest")
then
  assert(new Role("guest"));
end;

rule RestrictDocumentEditPage
  no-loop
  activation-group "permissions"
when
  c: PermissionCheck(name == "/docEdit.xhtml", action == "render", granted == false)
  Role(name == "member")
then
  c.grant();
  modify(c);
end;

rule RestrictDirectoryEditPage
  no-loop
  activation-group "permissions"
when
  c: PermissionCheck(name == "/dirEdit.xhtml", action == "render", granted == false)
  Role(name == "admin")
then
  c.grant();
  modify(c);
end;
