insert into User (username, password, name) values ('gavin', 'foobar', 'Gavin King')
insert into User (username, password, name) values ('demo', 'demo', 'Demo User')
insert into Hotel (id, address, city, zip) values (1, 'Tower Place, Buckhead', 'Atlanta', '30305')
insert into Hotel (id, address, city, zip) values (2, 'Union Square, Manhattan', 'NY', '11111')
insert into Hotel (id, address, city, zip) values (3, 'Super 8', 'WI', '54701')
insert into Hotel (id, address, city, zip) values (4, 'Red Roof Inn', 'WI', '54704')